# Generated by Django 5.2.4 on 2025-08-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("county", models.CharField(max_length=50)),
                ("postcode", models.CharField(max_length=10)),
            ],
        ),
    ]
